In [1]:
# Download dataset
import pandas as pd

url = "https://raw.githubusercontent.com/fivethirtyeight/guns-data/master/interactive_data.csv"
data = pd.read_csv(url)

data.head()

,Unnamed: 0,Intent,Gender,Age,Race,Deaths,Population,Rate
0,1,None selected,None selected,None selected,None selected,33599,316299978,10.6
1,2,None selected,None selected,None selected,White,22079,197369634,11.2
2,3,None selected,None selected,None selected,Black,7765,38896382,20.0
3,4,None selected,None selected,None selected,Hispanic,3007,54049078,5.6
4,5,None selected,None selected,None selected,Asian/Pacific Islander,442,16315561,2.7

In [39]:
# Clean intent data
# clean_intent_data = data[data['Intent'].notna() & ~data['Intent'].isin(['None selected', 'Unknown'])]
clean_intent_data = data[data['Intent'] != 'None selected']
clean_intent_data.head()

,Unnamed: 0,Intent,Gender,Age,Race,Deaths,Population,Rate
108,109,Suicide,None selected,None selected,None selected,21058,316299978,6.7
109,110,Suicide,None selected,None selected,White,18457,197369634,9.4
110,111,Suicide,None selected,None selected,Black,1111,38896382,2.9
111,112,Suicide,None selected,None selected,Hispanic,1057,54049078,2.0
112,113,Suicide,None selected,None selected,Asian/Pacific Islander,248,16315561,1.5

In [ ]:
# Verify: Nearly two-thirds of gun deaths are suicides, on uncleaned data
death_count = data['Deaths'].sum()

suicides_df = data[data['Intent'] == 'Suicide']
suicides_count = suicides_df['Deaths'].sum()

suicides_count / death_count

np.float64(0.3133747535250567)

In [40]:
# Verify: Nearly two-thirds of gun deaths are suicides
death_count = clean_intent_data['Deaths'].sum()

suicides_df = clean_intent_data[clean_intent_data['Intent'] == 'Suicide']
suicides_count = suicides_df['Deaths'].sum()

suicides_count / death_count

np.float64(0.6267518388029272)

In [35]:
# Verify: Around a third of all gun deaths are homicides
death_count = clean_intent_data['Deaths'].sum()

homicides_df = clean_intent_data[clean_intent_data['Intent'] == 'Homicide']
homicides_count = homicides_df['Deaths'].sum()

homicides_count / death_count

np.float64(0.35181518151815183)

In [48]:
# Clean intent, gender data
clean_intent_gender_data = data[(data['Intent'] != 'None selected') & (data['Gender'] != 'None selected')]
clean_intent_gender_data.head()

,Unnamed: 0,Intent,Gender,Age,Race,Deaths,Population,Rate
144,145,Suicide,Female,None selected,None selected,2896,160668110,1.8
145,146,Suicide,Female,None selected,White,2606,100162288,2.6
146,147,Suicide,Female,None selected,Black,121,20362385,0.6
147,148,Suicide,Female,None selected,Hispanic,116,26670924,0.4
148,149,Suicide,Female,None selected,Asian/Pacific Islander,33,8589119,0.4

In [53]:
# Verify: More than 85 percent of suicide victims are male.
suicides_df = clean_intent_gender_data[clean_intent_gender_data['Intent'] == 'Suicide']
suicides_count = suicides_df['Deaths'].sum()

male_suicides_df = suicides_df[suicides_df['Gender'] == 'Male']
male_suicides_count = male_suicides_df['Deaths'].sum()

male_suicides_count / suicides_count

np.float64(0.8624410860351643)

In [54]:
# Verify: Women constitue only 15 percent of the total homicide victims.
homicides_df = clean_intent_gender_data[clean_intent_gender_data['Intent'] == 'Homicide']
homicides_count = homicides_df['Deaths'].sum()

female_homicides_df = homicides_df[homicides_df['Gender'] == 'Female']
female_homicides_df = female_homicides_df['Deaths'].sum()

female_homicides_df / homicides_count

np.float64(0.15279495160533835)

In [59]:
# Clean intent, gender, age, race data
clean_data = data[~data[['Intent', 'Gender', 'Age', 'Race']].eq('None selected').any(axis=1)]
clean_data.head()

,Unnamed: 0,Intent,Gender,Age,Race,Deaths,Population,Rate
151,152,Suicide,Female,Under 15,White,19,15355910,0.1
152,153,Suicide,Female,Under 15,Black,1,4095428,0.0
153,154,Suicide,Female,Under 15,Hispanic,4,7330024,0.1
154,155,Suicide,Female,Under 15,Asian/Pacific Islander,1,1393440,0.1
155,156,Suicide,Female,Under 15,Other,0,1661877,0.0

In [63]:
# Verify: Around two-thirds of homicide victims who are males in the age-group of 15--34 are black.
filtered_df = clean_data[(clean_data['Intent'] == 'Homicide') & (clean_data['Gender'] == 'Male') & (clean_data['Age'] == '15 - 34')]
filtered_death_count = filtered_df['Deaths'].sum()

black_filtered_df = filtered_df[filtered_df['Race'] == 'Black']
back_filtered_death_count = black_filtered_df['Deaths'].sum()

back_filtered_death_count / filtered_death_count

np.float64(0.6612482748044778)